name: freeproxy
description: "Socks5 proxies for free"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.4
  
  # Database and storage
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.3
  
  # UI components
  flutter_svg: ^2.0.7  # For flag SVGs
  cached_network_image: ^3.4.1
  
  # Utils
  intl: ^0.20.2
  ulid: ^2.0.1
  crypto: ^3.0.6
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_secure_storage: ^9.2.4
  clipboard: ^0.1.3
  http: ^1.3.0
  socks5: ^0.2.0
  flutter_local_notifications: ^19.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
